### ISSUE TITLE
errors in the notebook

### ISSUE THREAD

**Issue by stonebig** [gapatino/Doing-frequentist-statistics-with-Scipy#3]
there seems to be some last minute, or automatic langa corrector issues:
- "virginica" is in your notebook code, but "verginica" is in the datas

**Comment by gapatino** [comment]
Hi stonebig, thank you for pointing out both this mistake and the typo on the CSV file. I have uploaded a new version of the dataset where the species is properly identified as "virginica", which then matches the code in the notebook, and that kept your correction of "Septal" for "Sepal". I apologize for any problems this may have caused you, and thank you again for the corrections. Please let me know if there are still issues after this change.

**Comment by stonebig** [comment]
super. I was interested by your talk, as a beginner in frequentism thing. thanks for having updated your reference material.
